version: '3.5'
services:
  night:
    image: mayrocolnago/php-vhost:latest
    container_name: night
    restart: always
    volumes:
      - .:/var/www/html
      - ./apache/php.ini:/usr/local/etc/php/php.ini:ro
      - ./apache/apache.conf:/etc/apache2/apache2.conf:ro
      - ./apache/host.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./apache/host.conf:/etc/apache2/sites-enabled/000-default.conf:ro
    healthcheck:
      test: curl --fail http://localhost/cron/run?code=AUTHKEY || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
      start_period: 60s

  nightdb:
    container_name: nightdb
    image: mariadb:10.5.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql # perhaps it is better to map the volume on a parent directory
    environment:
      MYSQL_ROOT_PASSWORD: root

  # nightrunner:
  #   container_name: nightrunner
  #   restart: always
  #   image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
  #   volumes:
  #     - ./runner:/etc/gitlab-runner:z
  #     - .:/var/www/html

networks:
  default:
    external:
      name: yournetwork
